name: Build

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "**"
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-auditable
        run: cargo install cargo-auditable

      - name: Build
        run: cargo auditable build --release --locked --target ${{ matrix.target }}
        env:
          CARGO_PROFILE_RELEASE_LTO: "fat"
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"

      - name: Rename artifact
        run: cp ./target/${{ matrix.target }}/release/am ./am-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: am-${{ matrix.target }}
          path: ./am-${{ matrix.target }}
